---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    jenkins_package_state: latest
    docker_users:
    - jenkins
  roles:
  - geerlingguy.java
  - geerlingguy.jenkins
  - geerlingguy.docker
